### ISSUE TITLE
Errors during encoding crash the app without user-visible explanation

### ISSUE THREAD

**Issue by kornelski** [sindresorhus/gifski-app#17]
https://github.com/sindresorhus/gifski-app/blob/a49430de68c66808925cfa214da385e1aeec56b8/Gifski/Gifski.swift#L89

`fatalError` seems to be a nuclear option which makes the app crash. From user perspective the app disappears without explanation.

`fatalError` shouldn't be used. Instead, the app should show a message box.

----

Example crash log:

> Application Specific Information:
Fatal error: Error with image 0: Error Domain=AVFoundationErrorDomain Code=-11869 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x60c0000598f0 {Error Domain=NSOSStatusErrorDomain Code=-12430 "(null)"}}: file /Users/sindresorhus/dev/oss/gifski-app/Gifski/Gifski.swift, line 73
 
> ViewBridge hint(s): (
    "<NSRemoteView 0x600000139e60> com.apple.appkit.xpc.openAndSavePanelService NSSavePanelService",
    "bridge key: most-recent-completion"
)

**Comment by sindresorhus** [comment]
Agreed. Even better if we show a dialog about posting the issue on GitHub.

Do you have the image the caused this issue? Would be helpful to investigate why it failed.

**Comment by sindresorhus** [comment]
We got sent the video clip for this issue privately and I looked into it. It uses the [QuickTime Animation](https://en.m.wikipedia.org/wiki/QuickTime_Animation) codec, which it seems AVFoundation cannot use out of the box.

`AVAsset` returns the following for it:

```
isPlayable => false
isExportable => true
isReadable => true
isComposable => true
```

When opening the video in QuickTime, it shows `Converting…` for some seconds.

**Comment by sindresorhus** [comment]
I've improved the supported video detection in https://github.com/sindresorhus/gifski-app/commit/67ac3cd6774ea0bb84880c29e1b37ee220701c16

**Comment by sindresorhus** [comment]
No crashes in the latest version 🎉
