### ISSUE TITLE
File size and frame rate defaults

### ISSUE THREAD

**Issue by kornelski** [sindresorhus/gifski-app#28]
To avoid creating huge/wasteful GIFs, I suggest having smart defaults.

* If resolution is >= 640px wide, halve it. Videos have chroma subsampling and compression artefacts that are wasteful in GIF, so halving resolution for GIF is a good idea anyway.
* If framerate is >= 24fps, halve it. Frames cost a lot in GIF.

**Comment by sindresorhus** [comment]
What do you mean by "halve it"? People expect to get the resolution they chose.

**Comment by kornelski** [comment]
I mean setting sliders in the UI to that value when the window is opened.

Instead of defaulting values set in the UI to values read directly from the video, default to values from the video adjusted to make more sense.

**Comment by sindresorhus** [comment]
Ah ok. Yes, I agree.

**Comment by LarsJK** [comment]
I added a fix for this. 

However the scale slider has a minimum value of 0.2. Should do something about this?

If I record a fullscreen recording it will be 3360 × 2100 with means I can't make a gif smaller than 672 x 420.

**Comment by LarsJK** [comment]
Maybe define a minimum dimension and set the minimum scale dynamically based on that..?

**Comment by kornelski** [comment]
I've made suggestion for the dimensions here https://github.com/sindresorhus/gifski-app/issues/25#issuecomment-373951951
