### ISSUE TITLE
Fix Xcode 10 warning

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/gifski-app#35]
When compiling Gifski.app in Xcode 10 beta, I get this warning:

```
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'gifski')
```

// @kornelski FYI

**Comment by kornelski** [comment]
I have no idea what a headermap is and what that thing is about.

**Comment by sindresorhus** [comment]
I tried setting the build settings `USE_HEADERMAP` and `ALWAYS_SEARCH_USER_PATHS` to `NO`, but then the bridging header could no longer import libgifski.

**Comment by kornelski** [comment]
https://developer.apple.com/search/?q=headermap

> No results were found. Please try a different keyword.

I'm surprised there's no KB article for this, so I've filed a rdar about it being undocumented.


----

I think adding `USER_HEADER_SEARCH_PATHS = "$(SRCROOT)/gifski-api";` to project config should help.

**Comment by sindresorhus** [comment]
Turns out is enough to just set `ALWAYS_SEARCH_USER_PATHS` to `NO` to silence Xcode. No need to touch `USE_HEADERMAP`.

**Comment by EricShapiro** [comment]
We had the same error message with Xcode 10. The fix was to add a few missing header files to the project itself - just having them in the same directory as the source files is no longer sufficient. (This is the opposite advice Apple gave us 10 years ago, but that isn't much of a surprise)

**Comment by martinwinter** [comment]
> https://developer.apple.com/search/?q=headermap
> 
> > No results were found. Please try a different keyword.
> 
> I'm surprised there's no KB article for this, so I've filed a rdar about it being undocumented.
> 
> I think adding `USER_HEADER_SEARCH_PATHS = "$(SRCROOT)/gifski-api";` to project config should help, but I'm currently fighting with other problems around gcc/Xcode-10/Mojave combo incompatibilities, so I can't verify.

For future references via search, here is the documentation: https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/build_system_release_notes_for_xcode_10?language=objc

**Comment by MichaelCunliffeThompson** [comment]
I'm hoping to do some application programming with SFML. Alas I know nothing about builds II apologize for that).   Coud someone help me with how to  "just set ALWAYS_SEARCH_USER_PATHS to NO".  _'d be most grateful as I'm completely stuck here...
Mike

**Comment by martinwinter** [comment]
> I'm hoping to do some application programming with SFML. Alas I know nothing about builds II apologize for that). Coud someone help me with how to "just set ALWAYS_SEARCH_USER_PATHS to NO". _'d be most grateful as I'm completely stuck here...

* Open the project in Xcode.
* In the navigator (sidebar on the left), select the project icon (should be the first item).
* In the main area, you should see several items at the top, select the one named “Build Settings”.
* In the search field in the top right, paste `ALWAYS_SEARCH_USER_PATHS`.
* This will reduce the items to one or two. Select “Always Search User Paths (Deprecated)”.
* Choose “No” from the little pop-up menu (if multiple columns are visible, choose the right-most column).
