### ISSUE TITLE
Add FPS option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/gifski-app#4]
It could be useful to have an FPS (Frames per second) option in the save dialog. It should be a slider that goes from `5` to `30`.

**Comment by alimuqaddas** [comment]
Yes, thats what i was looking for.

**Comment by kornelski** [comment]
FPS change is something I want to have in the CLI version as well, so I'll add it to the underlying library.

**Comment by sindresorhus** [comment]
Here's how it looks:

![screen shot 2018-02-24 at 15 53 03](https://user-images.githubusercontent.com/170270/36627793-dffe3870-197a-11e8-8c24-37be497f0e50.png)
