### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/gifski-app#42]
In Organizer in Xcode, I see some users are getting a crash at:

https://github.com/sindresorhus/gifski-app/blob/eac104f38a1956351d1265b7af7d456c95c31bfc/Gifski/MainWindowController.swift#L124

But there's no error message, so it's hard to guess what the issue is.

This crash has been reported for every version of Gifski since it was first released.

This is what I'm seeing in Xcode:

<img width="874" alt="screen shot 2018-10-22 at 10 49 17" src="https://user-images.githubusercontent.com/170270/47277224-2b46f680-d5e8-11e8-9635-634a713aa313.png">

Is there anything we can do to improve the logging of this error? I assumed `fatalError` would include the actual error message, but it seems not. At least not in the crash report we get from Apple.

[D3n6t7-Uxh_FcdK-IatJgq.xccrashpoint.zip](https://github.com/sindresorhus/gifski-app/files/2500119/D3n6t7-Uxh_FcdK-IatJgq.xccrashpoint.zip)

**Comment by LarsJK** [comment]
We could use Crashlytics: https://firebase.google.com/docs/crashlytics/customize-crash-reports#add_custom_logs

**Comment by sindresorhus** [comment]
That guide is for iOS. Fabrics Crashlytics supported macOS, but Google has given no indication of macOS support for Firebase Crashlytics. I also don't trust Google.

**Comment by LarsJK** [comment]
What about logging the error with SwiftyBeaver?

**Comment by sindresorhus** [comment]
That could be an option, but how would we get the logs? We would still have to have them uploaded somewhere.

**Comment by sindresorhus** [comment]
SwiftyBeaver looks good for logging, but it doesn't do automatic crash reporting. I went with Fabrics Crashlytics. It's still operational even with the new Firebase Crashlytics.

**Comment by sindresorhus** [comment]
This was fixed by https://github.com/sindresorhus/gifski-app/commit/833fd28d1eed5c989a82af922229b35a59c1f560.
