### ISSUE TITLE
Integrate with Mojave screen recording/QuickLook UI

### ISSUE THREAD

**Issue by jrunning** [sindresorhus/gifski-app#62]
I don't *think* this is a duplicate of #47, but please close if it is.

macOS Mojave has a great new [screen recording UI](https://support.apple.com/en-us/HT208721#mojave). When you finish a screen recording, it shows a thumbnail in the corner of the screen. You can right-click on the thumbnail to see this menu:

<img width="306" alt="screen shot 2019-02-13 at 9 46 15 am" src="https://user-images.githubusercontent.com/117983/52724171-72c90800-2f74-11e9-9b4c-6468dca6a924.png">

Or you can left-click on the thumbnail to open the recording in a QuickLook window, which has a "Share" button that lets you send the recording to another app:

<img width="342" alt="screen shot 2019-02-13 at 9 38 06 am" src="https://user-images.githubusercontent.com/117983/52723446-27fac080-2f73-11e9-8457-75bee438ba57.png">

It would streamline the screen recording workflow a lot if Gifski could be added to one or both of these menus.

(On a related note—and I could open a separate issue for this if anyone thinks it's worthwhile—it might be useful to have an option for Gifski to open newly encoded GIFs in QuickLook, especially in Mojave.)

**Comment by sindresorhus** [comment]
> macOS Mojave has a great new [screen recording UI](https://support.apple.com/en-us/HT208721#mojave). When you finish a screen recording, it shows a thumbnail in the corner of the screen. You can right-click on the thumbnail to see this menu:

There's unfortunately no way for apps to add items to that menu. It's very surprising it doesn't have a `Open With` menu, like when right-clicking a file in Finder. That would solve this quite nicely. I have opened a feature request with Apple about this: https://openradar.appspot.com/radar?id=4966552080220160

> Or you can left-click on the thumbnail to open the recording in a QuickLook window, which has a "Share" button that lets you send the recording to another app:

Yeah, we could consider having a share extension, but this is really not what Share extensions are for, and we might not be allowed by Apple to use it like that. Share extensions should not just be "Open With".

> (On a related note—and I could open a separate issue for this if anyone thinks it's worthwhile—it might be useful to have an option for Gifski to open newly encoded GIFs in QuickLook, especially in Mojave.)

We're working on a better "conversion completed" UI in #57 which will give you a "Reveal in Finder" button. You can then press Space after that to look at the GIF in Quick Look.

**Comment by sindresorhus** [comment]
I'm gonna close this as it's not something we can work around. We just have to wait for Apple to do the right thing.
