### ISSUE TITLE
Allows creating gifs without a filename extension

### ISSUE THREAD

**Issue by geordiemhall** [sindresorhus/gifski-app#67]
I was just just doing some throwaway gifs and quickly typed "test" into the filename field, expecting the ".gif" extension to be added automatically once I pressed enter, but instead it just dutifully created a file named "test" without any extension.

Photoshop and those sort of apps usually just add the extension for you when you click Save (or press enter) based on the currently selected file type. 

In Gifski's case, GIF is the only possible file type, so I think it'd be fine to add ".gif" to the user's filename if they didn't include one themselves.

**Comment by sindresorhus** [comment]
Thanks for reporting :)
