### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by indexzero** [sindresorhus/gifski-app#70]
> Great job on `gifski` – previous Gif Brewery user and never looking back ❤️ 

As a user I make gifs for primarily two reasons:

1. **Converting screen captures** Gifski crushes it. 
2. **Converting `webp` search results on Giphy** webp is not supported so I 😭 a little.

I want to say I can help contribute the fix, but I will be honest about my availability. Please keep up the awesome work on gifski.

p.s. I would happily have paid like $3.99 for this in the App Store.

**Comment by sindresorhus** [comment]
> Converting webp search results on Giphy webp is not supported so I 😭 a little.

Do you mean that the GIFs on Giphy are in WebP format?

> p.s. I would happily have paid like $3.99 for this in the App Store.

Hehe. Thanks for the encouragement, but Gifski will be forever free.

**Comment by indexzero** [comment]
> Do you mean that the GIFs on Giphy are in WebP format? I have never seen that.

Yes. Many are. It's not consistent.

**Comment by sindresorhus** [comment]
I think supporting WebP as input is a bit out of scope for this app.

It would be better to create a Chrome extension that uses the [Giphy API](https://developers.giphy.com/docs/) to inject a GIF download link on every Giphy page.
