### ISSUE TITLE
Enjoying (null)?

### ISSUE THREAD

**Issue by aried3r** [sindresorhus/gifski-app#75]
In this case, I think, I do not enjoy it. :)

![Screenshot 2019-04-26 at 15 14 26](https://user-images.githubusercontent.com/1301152/56810762-5f210400-6837-11e9-9ba1-1f8d6b3047cb.png)
![Screenshot 2019-04-26 at 15 18 23](https://user-images.githubusercontent.com/1301152/56810763-5f210400-6837-11e9-9760-4aaff82990e5.png)

**Comment by sindresorhus** [comment]
It’s a bug in an Apple API. Nothing we can do anything about it, unfortunately:

https://forums.developer.apple.com/thread/115449

**Comment by aried3r** [comment]
Oh, that's good to know. Thanks for the quick response! I'm gonna close this issue then.
