### ISSUE TITLE
App doesn't launch

### ISSUE THREAD

**Issue by paulirish** [sindresorhus/gifski-app#8]
After installing from Mac Store it fails to run

Running from Finder I get: 
> The application “Gifski.app” can’t be opened.

Running from terminal:

```
❯ /Applications/Gifski.app/Contents/MacOS/Gifski
dyld: Symbol not found: __TMSi
  Referenced from: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftos.dylib
  Expected in: /Applications/Gifski.app/Contents/MacOS/../Frameworks/libswiftCore.dylib
 in /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftos.dylib
fish: '/Applications/Gifski.app/Conten…' terminated by signal SIGABRT (Abort)
```

I'm gonna try building from source now.. :p 

update: i gave up building from source after this error building `imagequant-sys v2.11.9`: `unsupported option '-fopenmp'`. not ready to upgrade my clang. :/

**Comment by kornelski** [comment]
First, congratulations. According to Google you're the first person on the web to be missing the `__TMSi` symbol.

From the log it seems like a bizarre incompatibility of Swift in your Xcode installation with Swift used in the app. Why did it involve Xcode at all in loading of a regular app, I have no idea.

What's your exact macOS version? 

----

As for the build, the GCC version is faster. `brew install gcc` should be enough to make it compile.

**Comment by sindresorhus** [comment]
> From the log it seems like a bizarre incompatibility of Swift in your Xcode installation with Swift used in the app.

Yeah, that should not even happen. The Swift framework is bundled in the app.

**Comment by sindresorhus** [comment]
According to iTunes Connect, there has been only one case of this crash.

The same computer that experienced this crash also got:

```
Symbol not found: __T0s14_VaListBuilderC15gpRegistersUsedSivpWvd + 0
```

**Comment by paulirish** [comment]
> What's your exact macOS version?

I actually upgraded to High Sierra just to use gifski. :) 

I'm at `10.13.3 (17D47)`

My installed XCode version is `8.3.3` fwiw. brew wants me to upgrade that for gcc, so we'll know if xcode 9.2 installed fixes running the app. 

Not a huge deal, guys. :) But figured I'd make the issue.

**Comment by paulirish** [comment]
yup. xcode 9.2 installed and the original problem went away. bizarre.

**Comment by kornelski** [comment]
Dupe #12
